Add custom status check to Github on Terraform runs
aeternity/terraform-aws-testnet-api pull request #15
Opened 2019-10-28 14:37 UTC by IvayloPapazov

ref https://github.com/aeternity/infrastructure/issues/432

2019-11-01 08:40 UTC, venimus approved these changes

2019-11-01 08:41 UTC, venimus requested changes
This should be a script that is hosted in infrastructure

2019-11-01 12:12 UTC, venimus approved these changes

2019-11-05 09:21 UTC, dincho approved these changes

2019-11-05 09:32 UTC, merged